export const DEFAULT_BLACKBAUD_FIELD_MAPPINGS = [
  {
    mapping_key: "constituents.blackbaud_constituent_id",
    app_entity: "constituents",
    app_field: "blackbaud_constituent_id",
    blackbaud_object: "Constituent",
    blackbaud_field: "id",
    selection_rule: "Store exact NXT constituent ID",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Primary link key",
  },
  {
    mapping_key: "constituents.name",
    app_entity: "constituents",
    app_field: "name",
    blackbaud_object: "Constituent",
    blackbaud_field: "name",
    selection_rule:
      "Use Constituent.name, which is Blackbaud's computed display/full name",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "",
  },
  {
    mapping_key: "constituents.email",
    app_entity: "constituents",
    app_field: "email",
    blackbaud_object: "Constituent",
    blackbaud_field: "email.address",
    selection_rule:
      "Use Constituent.email.address only when Constituent.email.primary = true; if not primary or missing, leave blank",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "",
  },
  {
    mapping_key: "constituents.phone",
    app_entity: "constituents",
    app_field: "phone",
    blackbaud_object: "Constituent",
    blackbaud_field: "phone.number",
    selection_rule:
      "Use Constituent.phone.number only when Constituent.phone.primary = true; if not primary or missing, leave blank",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "",
  },
  {
    mapping_key: "constituents.organization",
    app_entity: "constituents",
    app_field: "organization",
    blackbaud_object: "Constituent / employment",
    blackbaud_field: "tbd",
    selection_rule:
      "Decide whether this should come from primary organization, employer, or another NXT field",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Constituent (Get) does not expose a direct organization/employer field",
  },
  {
    mapping_key: "constituents.lookup_id",
    app_entity: "constituents",
    app_field: "lookup_id",
    blackbaud_object: "Constituent",
    blackbaud_field: "lookup_id",
    selection_rule: "Use the Blackbaud user-defined constituent identifier",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Optional secondary identifier",
  },
  {
    mapping_key: "constituents.preferred_name",
    app_entity: "constituents",
    app_field: "preferred_name",
    blackbaud_object: "Constituent",
    blackbaud_field: "preferred_name",
    selection_rule:
      "Use Constituent.preferred_name when present; otherwise fall back to Constituent.first or Constituent.name in the app",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Individuals only",
  },
  {
    mapping_key: "constituent_edit.first",
    app_entity: "constituent_edit",
    app_field: "first",
    blackbaud_object: "ConstituentEdit",
    blackbaud_field: "first",
    selection_rule:
      "For linked individual constituents only; push only when intentionally editing the canonical first name in NXT",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "Individuals only; max 50 chars",
  },
  {
    mapping_key: "constituent_edit.middle",
    app_entity: "constituent_edit",
    app_field: "middle",
    blackbaud_object: "ConstituentEdit",
    blackbaud_field: "middle",
    selection_rule:
      "For linked individual constituents only; push only when intentionally editing the canonical middle name in NXT",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "Individuals only; max 50 chars",
  },
  {
    mapping_key: "constituent_edit.last",
    app_entity: "constituent_edit",
    app_field: "last",
    blackbaud_object: "ConstituentEdit",
    blackbaud_field: "last",
    selection_rule:
      "For linked individual constituents only; push only when intentionally editing the canonical last name in NXT",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "Individuals only; max 100 chars",
  },
  {
    mapping_key: "constituent_edit.preferred_name",
    app_entity: "constituent_edit",
    app_field: "preferred_name",
    blackbaud_object: "ConstituentEdit",
    blackbaud_field: "preferred_name",
    selection_rule:
      "For linked individual constituents only; push when the app is explicitly updating preferred name",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "Individuals only; max 50 chars",
  },
  {
    mapping_key: "constituent_edit.lookup_id",
    app_entity: "constituent_edit",
    app_field: "lookup_id",
    blackbaud_object: "ConstituentEdit",
    blackbaud_field: "lookup_id",
    selection_rule:
      "Only push if the organization wants the app to manage constituent lookup IDs; otherwise leave NXT as the source of truth",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "High-governance field; likely admin-only",
  },
  {
    mapping_key: "constituent_edit.inactive",
    app_entity: "constituent_edit",
    app_field: "inactive",
    blackbaud_object: "ConstituentEdit",
    blackbaud_field: "inactive",
    selection_rule:
      "Only push from an admin/reviewer workflow with explicit intent; do not infer from local app inactivity",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "High-risk write-back",
  },
  {
    mapping_key: "constituent_edit.gives_anonymously",
    app_entity: "constituent_edit",
    app_field: "gives_anonymously",
    blackbaud_object: "ConstituentEdit",
    blackbaud_field: "gives_anonymously",
    selection_rule:
      "Only push from an explicit profile/privacy workflow, not from prospect workflow forms",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "Privacy-sensitive",
  },
  {
    mapping_key: "constituent_edit.requests_no_email",
    app_entity: "constituent_edit",
    app_field: "requests_no_email",
    blackbaud_object: "ConstituentEdit",
    blackbaud_field: "requests_no_email",
    selection_rule:
      "Only push from an explicit communications preferences workflow",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "Communications preference",
  },
  {
    mapping_key: "constituent_edit.is_solicitor",
    app_entity: "constituent_edit",
    app_field: "is_solicitor",
    blackbaud_object: "ConstituentEdit",
    blackbaud_field: "is_solicitor",
    selection_rule:
      "Do not push automatically from app solicitor-request workflows; reviewer/admin confirmation required",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "Keep manual approval gate",
  },
  {
    mapping_key: "constituent_edit.organization_name",
    app_entity: "constituent_edit",
    app_field: "organization_name",
    blackbaud_object: "ConstituentEdit",
    blackbaud_field: "name",
    selection_rule:
      "For linked organization constituents only; push to ConstituentEdit.name because that field is editable only for organization records",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "Organizations only; do not use for individuals",
  },
  {
    mapping_key: "constituents.address",
    app_entity: "constituents",
    app_field: "address",
    blackbaud_object: "Constituent",
    blackbaud_field: "address.formatted_address",
    selection_rule:
      "Use Constituent.address.formatted_address only when Constituent.address.preferred = true; otherwise leave blank",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Preferred mailing address only",
  },
  {
    mapping_key: "constituent_lifetime_giving.total_giving",
    app_entity: "constituent_lifetime_giving",
    app_field: "total_giving",
    blackbaud_object: "LifetimeGivingRead",
    blackbaud_field: "total_giving.value",
    selection_rule:
      "Pull cumulative lifetime giving from GET /constituents/{id}/givingsummary/lifetimegiving",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Good candidate for a read-only donor profile summary",
  },
  {
    mapping_key: "constituent_lifetime_giving.total_received_giving",
    app_entity: "constituent_lifetime_giving",
    app_field: "total_received_giving",
    blackbaud_object: "LifetimeGivingRead",
    blackbaud_field: "total_received_giving.value",
    selection_rule:
      "Pull actual received giving total from GET /constituents/{id}/givingsummary/lifetimegiving",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Useful when you want received vs pledged totals separated",
  },
  {
    mapping_key: "constituent_lifetime_giving.total_pledge_balance",
    app_entity: "constituent_lifetime_giving",
    app_field: "total_pledge_balance",
    blackbaud_object: "LifetimeGivingRead",
    blackbaud_field: "total_pledge_balance.value",
    selection_rule:
      "Pull outstanding pledge balance from GET /constituents/{id}/givingsummary/lifetimegiving",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Good candidate for fundraiser context, not workflow state",
  },
  {
    mapping_key: "constituent_lifetime_giving.total_soft_credits",
    app_entity: "constituent_lifetime_giving",
    app_field: "total_soft_credits",
    blackbaud_object: "LifetimeGivingRead",
    blackbaud_field: "total_soft_credits.value",
    selection_rule:
      "Pull cumulative soft credits from GET /constituents/{id}/givingsummary/lifetimegiving",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Only surface if your team cares about soft-credit history in the app",
  },
  {
    mapping_key: "constituent_lifetime_giving.total_years_given",
    app_entity: "constituent_lifetime_giving",
    app_field: "total_years_given",
    blackbaud_object: "LifetimeGivingRead",
    blackbaud_field: "total_years_given",
    selection_rule:
      "Pull computed giving-years count from GET /constituents/{id}/givingsummary/lifetimegiving",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Good engagement summary metric",
  },
  {
    mapping_key: "constituent_lifetime_giving.consecutive_years_given",
    app_entity: "constituent_lifetime_giving",
    app_field: "consecutive_years_given",
    blackbaud_object: "LifetimeGivingRead",
    blackbaud_field: "consecutive_years_given",
    selection_rule:
      "Pull computed consecutive-giving-years count from GET /constituents/{id}/givingsummary/lifetimegiving",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Useful for stewardship context",
  },
  {
    mapping_key: "constituent_fundraiser_assignments.assignment_id",
    app_entity: "constituent_fundraiser_assignments",
    app_field: "assignment_id",
    blackbaud_object: "FundraiserAssignmentRead",
    blackbaud_field: "id",
    selection_rule:
      "Pull assignment record ID from GET /constituents/{id}/fundraiserassignments with include_inactive=false by default",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Read-only assignment identifier for linked records",
  },
  {
    mapping_key: "constituent_fundraiser_assignments.fundraiser_id",
    app_entity: "constituent_fundraiser_assignments",
    app_field: "fundraiser_id",
    blackbaud_object: "FundraiserAssignmentRead",
    blackbaud_field: "fundraiser_id",
    selection_rule:
      "Pull active assignment fundraiser IDs from GET /constituents/{id}/fundraiserassignments?include_inactive=false unless a historical admin view needs inactive rows",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Best candidate for showing NXT fundraiser ownership",
  },
  {
    mapping_key: "constituent_fundraiser_assignments.amount",
    app_entity: "constituent_fundraiser_assignments",
    app_field: "amount",
    blackbaud_object: "FundraiserAssignmentRead",
    blackbaud_field: "amount.value",
    selection_rule:
      "Pull assignment amount exactly as returned for the fundraiser assignment",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Read-only planning context",
  },
  {
    mapping_key: "constituent_fundraiser_assignments.appeal_id",
    app_entity: "constituent_fundraiser_assignments",
    app_field: "appeal_id",
    blackbaud_object: "FundraiserAssignmentRead",
    blackbaud_field: "appeal_id",
    selection_rule:
      "Pull linked appeal ID when present on the fundraiser assignment",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Optional campaign context",
  },
  {
    mapping_key: "constituent_fundraiser_assignments.campaign_id",
    app_entity: "constituent_fundraiser_assignments",
    app_field: "campaign_id",
    blackbaud_object: "FundraiserAssignmentRead",
    blackbaud_field: "campaign_id",
    selection_rule:
      "Pull linked campaign ID when present on the fundraiser assignment",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Optional campaign context",
  },
  {
    mapping_key: "constituent_fundraiser_assignments.fund_id",
    app_entity: "constituent_fundraiser_assignments",
    app_field: "fund_id",
    blackbaud_object: "FundraiserAssignmentRead",
    blackbaud_field: "fund_id",
    selection_rule:
      "Pull linked fund ID when present on the fundraiser assignment",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Optional restricted-fund context",
  },
  {
    mapping_key: "constituent_fundraiser_assignments.start",
    app_entity: "constituent_fundraiser_assignments",
    app_field: "start",
    blackbaud_object: "FundraiserAssignmentRead",
    blackbaud_field: "start",
    selection_rule: "Pull assignment start date exactly as returned",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Good for assignment age and active-range displays",
  },
  {
    mapping_key: "constituent_fundraiser_assignments.end",
    app_entity: "constituent_fundraiser_assignments",
    app_field: "end",
    blackbaud_object: "FundraiserAssignmentRead",
    blackbaud_field: "end",
    selection_rule:
      "Pull assignment end date when present; omit for open-ended active assignments",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Useful only when showing inactive or historical assignments",
  },
  {
    mapping_key: "constituent_fundraiser_assignments.type",
    app_entity: "constituent_fundraiser_assignments",
    app_field: "type",
    blackbaud_object: "FundraiserAssignmentRead",
    blackbaud_field: "type",
    selection_rule:
      "Pull solicitor-type label exactly as returned by GET /constituents/{id}/fundraiserassignments",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Examples include Major Donor, Fund, or Volunteer",
  },
  {
    mapping_key: "prospects.blackbaud_constituent_id",
    app_entity: "prospects",
    app_field: "blackbaud_constituent_id",
    blackbaud_object: "Constituent",
    blackbaud_field: "id",
    selection_rule: "Match to linked constituent",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Added for linking",
  },
  {
    mapping_key: "prospects.ask_amount",
    app_entity: "prospects",
    app_field: "ask_amount",
    blackbaud_object: "Opportunity rollup or local ranking",
    blackbaud_field: "tbd",
    selection_rule: "Keep local rollup until opportunity sync is defined",
    direction: "local only",
    source_of_truth: "App",
    notes: "",
  },
  {
    mapping_key: "prospects.status",
    app_entity: "prospects",
    app_field: "status",
    blackbaud_object: "Prospect / opportunity rollup",
    blackbaud_field: "tbd",
    selection_rule: "Keep local until opportunity sync is stable",
    direction: "local only",
    source_of_truth: "App",
    notes: "",
  },
  {
    mapping_key: "prospect_pool.email",
    app_entity: "prospect_pool",
    app_field: "email",
    blackbaud_object: "Constituent",
    blackbaud_field: "email.address",
    selection_rule:
      "Use Constituent.email.address only when Constituent.email.primary = true and the pool item is linked",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Otherwise local",
  },
  {
    mapping_key: "prospect_pool.phone",
    app_entity: "prospect_pool",
    app_field: "phone",
    blackbaud_object: "Constituent",
    blackbaud_field: "phone.number",
    selection_rule:
      "Use Constituent.phone.number only when Constituent.phone.primary = true and the pool item is linked",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "Otherwise local",
  },
  {
    mapping_key: "submissions.notes",
    app_entity: "submissions",
    app_field: "notes",
    blackbaud_object: "Contact report / action notes",
    blackbaud_field: "tbd",
    selection_rule: "Candidate future write-back; defer for now",
    direction: "local only",
    source_of_truth: "App",
    notes: "Defer",
  },
  {
    mapping_key: "submissions.blackbaud_action_id",
    app_entity: "submissions",
    app_field: "blackbaud_action_id",
    blackbaud_object: "Action",
    blackbaud_field: "id",
    selection_rule: "Store the created RE NXT action ID after successful write-back",
    direction: "pull",
    source_of_truth: "Blackbaud NXT",
    notes: "For future action sync",
  },
  {
    mapping_key: "submissions.blackbaud_sync_status",
    app_entity: "submissions",
    app_field: "blackbaud_sync_status",
    blackbaud_object: "Action sync lifecycle",
    blackbaud_field: "n/a",
    selection_rule:
      "Track whether the local submission is pending, synced, skipped, or failed against Blackbaud",
    direction: "local only",
    source_of_truth: "App",
    notes: "Operational sync state only",
  },
  {
    mapping_key: "submissions.blackbaud_sync_error",
    app_entity: "submissions",
    app_field: "blackbaud_sync_error",
    blackbaud_object: "Action sync lifecycle",
    blackbaud_field: "n/a",
    selection_rule:
      "Store the latest Blackbaud sync error for reviewer/admin troubleshooting",
    direction: "local only",
    source_of_truth: "App",
    notes: "Operational sync state only",
  },
  {
    mapping_key: "action.summary",
    app_entity: "action",
    app_field: "summary",
    blackbaud_object: "Action",
    blackbaud_field: "summary",
    selection_rule: "Map combined update summary into the Blackbaud action summary",
    direction: "push",
    source_of_truth: "App",
    notes: "Character limit 255",
  },
  {
    mapping_key: "action.description",
    app_entity: "action",
    app_field: "description",
    blackbaud_object: "Action",
    blackbaud_field: "description",
    selection_rule:
      "Concatenate action notes and next step into the Blackbaud action description",
    direction: "push",
    source_of_truth: "App",
    notes: "",
  },
  {
    mapping_key: "action.constituent_id",
    app_entity: "action",
    app_field: "constituent_id",
    blackbaud_object: "Action",
    blackbaud_field: "constituent_id",
    selection_rule: "Use the linked constituent's stored blackbaud_constituent_id",
    direction: "push",
    source_of_truth: "Blackbaud NXT",
    notes: "Required for CreateAction",
  },
  {
    mapping_key: "action.date",
    app_entity: "action",
    app_field: "date",
    blackbaud_object: "Action",
    blackbaud_field: "date",
    selection_rule: "Use the update submission date in ISO-8601 format",
    direction: "push",
    source_of_truth: "App",
    notes: "Required for CreateAction",
  },
  {
    mapping_key: "action.category",
    app_entity: "action",
    app_field: "category",
    blackbaud_object: "Action",
    blackbaud_field: "category",
    selection_rule:
      "Map interaction type to Blackbaud values: call -> Phone Call, visit/event -> Meeting, email -> Email, otherwise Task/Other",
    direction: "push",
    source_of_truth: "App",
    notes: "Required for CreateAction",
  },
  {
    mapping_key: "action.direction",
    app_entity: "action",
    app_field: "direction",
    blackbaud_object: "Action",
    blackbaud_field: "direction",
    selection_rule: "Default to Outbound unless the app later captures inbound direction",
    direction: "push",
    source_of_truth: "App",
    notes: "",
  },
  {
    mapping_key: "action.author",
    app_entity: "action",
    app_field: "author",
    blackbaud_object: "Action",
    blackbaud_field: "author",
    selection_rule: "Use the signed-in user's display name when available",
    direction: "push",
    source_of_truth: "App",
    notes: "Optional",
  },
  {
    mapping_key: "action.completed",
    app_entity: "action",
    app_field: "completed",
    blackbaud_object: "Action",
    blackbaud_field: "completed",
    selection_rule:
      "Set true only when the app intentionally marks the action complete; otherwise leave false or omit",
    direction: "push",
    source_of_truth: "App",
    notes: "Relevant for ActionEdit and optional on CreateAction",
  },
  {
    mapping_key: "action.completed_date",
    app_entity: "action",
    app_field: "completed_date",
    blackbaud_object: "Action",
    blackbaud_field: "completed_date",
    selection_rule:
      "When completed is true, send the completion timestamp in ISO-8601 format",
    direction: "push",
    source_of_truth: "App",
    notes: "Relevant for ActionEdit and optional on CreateAction",
  },
  {
    mapping_key: "action.outcome",
    app_entity: "action",
    app_field: "outcome",
    blackbaud_object: "Action",
    blackbaud_field: "outcome",
    selection_rule:
      "Only send when the app can confidently map the result to Successful or Unsuccessful",
    direction: "push",
    source_of_truth: "App",
    notes: "Defer until action outcome UX exists",
  },
  {
    mapping_key: "action.type",
    app_entity: "action",
    app_field: "type",
    blackbaud_object: "Action",
    blackbaud_field: "type",
    selection_rule:
      "Optional subtype that complements category; use only after confirming the allowed Action table values in NXT",
    direction: "push",
    source_of_truth: "App",
    notes: "Defer until action type taxonomy is defined",
  },
  {
    mapping_key: "action.update",
    app_entity: "action",
    app_field: "update",
    blackbaud_object: "Action",
    blackbaud_field: "PATCH /constituent/v1/actions/{action_id}",
    selection_rule:
      "Use when a local synced submission is intentionally edited and the matching NXT action should be revised in place",
    direction: "push",
    source_of_truth: "App",
    notes: "Use stored submissions.blackbaud_action_id",
  },
  {
    mapping_key: "action.delete",
    app_entity: "action",
    app_field: "delete",
    blackbaud_object: "Action",
    blackbaud_field: "DELETE /constituent/v1/actions/{action_id}",
    selection_rule:
      "Only delete when a synced local submission is explicitly removed or replaced; never auto-delete during normal edits",
    direction: "push",
    source_of_truth: "App",
    notes: "Use stored submissions.blackbaud_action_id",
  },
];

export function getDefaultBlackbaudFieldMappings() {
  return DEFAULT_BLACKBAUD_FIELD_MAPPINGS.map((mapping) => ({ ...mapping }));
}

export function mergeBlackbaudFieldMappings(overrides = []) {
  const overrideMap = new Map(
    overrides.map((item) => [item.mapping_key, item]),
  );

  const merged = getDefaultBlackbaudFieldMappings().map((mapping) => ({
    ...mapping,
    ...(overrideMap.get(mapping.mapping_key) || {}),
  }));

  for (const override of overrides) {
    if (!overrideMap.has(override.mapping_key)) continue;
    if (!merged.some((item) => item.mapping_key === override.mapping_key)) {
      merged.push(override);
    }
  }

  return merged.sort((a, b) => {
    if (a.app_entity !== b.app_entity) {
      return a.app_entity.localeCompare(b.app_entity);
    }
    return a.app_field.localeCompare(b.app_field);
  });
}
